SKILL_NAME = "test_generator"
SKILL_DESCRIPTION = "Génère automatiquement des tests unitaires Python à partir de fonctions et fichiers"
SKILL_VERSION = "1.0.0"

import ast
from datetime import datetime
from pathlib import Path


try:
    from file_tools import read_file, write_file
except ImportError:
    read_file = None
    write_file = None


def run(action, **kwargs):
    try:
        action_name = str(action or "").strip().lower()

        if action_name == "analyze_function":
            return _analyze_function(kwargs.get("code", ""))

        if action_name == "analyze_file":
            return _analyze_file(kwargs.get("path", ""))

        if action_name == "generate":
            return _generate(
                kwargs.get("function_name", ""),
                kwargs.get("params", []),
                kwargs.get("returns", ""),
                kwargs.get("test_cases", []),
            )

        return _error(f"Action inconnue: {action}")
    except Exception as error:
        return _error(str(error))


def _analyze_function(code):
    if not code:
        return _error("code est requis")

    tree = ast.parse(code)
    functions = [node for node in tree.body if isinstance(node, ast.FunctionDef)]

    if not functions:
        return _error("Aucune fonction detectee")

    function = functions[0]
    params = _get_params(function)
    returns = _get_return_summary(function)
    test_code = _build_unittest(function.name, params, returns, [])

    return {
        "success": True,
        "test_code": test_code,
        "file_path": "",
        "error": "",
    }


def _analyze_file(path):
    file_path = Path(path)

    if not file_path.exists():
        return _error(f"Fichier introuvable: {file_path}")

    if file_path.suffix != ".py":
        return _error("Fichier Python attendu")

    source = _read_text(file_path)
    tree = ast.parse(source)
    functions = [
        node for node in tree.body
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")
    ]

    if not functions:
        return _error("Aucune fonction detectee")

    imports = [f"from {file_path.stem} import {function.name}" for function in functions]
    tests = []

    for function in functions:
        tests.append(_build_test_method(function.name, _get_params(function), []))

    test_code = _wrap_unittest(imports, tests)
    output_path = file_path.with_name(f"test_{file_path.stem}.py")
    _write_text(output_path, test_code)

    return {
        "success": True,
        "test_code": test_code,
        "file_path": str(output_path),
        "error": "",
    }


def _generate(function_name, params, returns, test_cases):
    if not function_name:
        return _error("function_name est requis")

    if params is None:
        params = []

    if test_cases is None:
        test_cases = []

    test_code = _build_unittest(function_name, params, returns, test_cases)

    return {
        "success": True,
        "test_code": test_code,
        "file_path": "",
        "error": "",
    }


def _build_unittest(function_name, params, returns, test_cases):
    imports = [
        f"# Generated by MILODO test_generator on {datetime.utcnow().isoformat()}Z",
        "import unittest",
        f"from target_module import {function_name}",
    ]
    tests = [_build_test_method(function_name, params, test_cases, returns)]
    return _wrap_unittest(imports, tests)


def _wrap_unittest(imports, tests):
    lines = []
    lines.extend(imports)
    lines.append("")
    lines.append("")
    lines.append("class GeneratedTests(unittest.TestCase):")

    for test in tests:
        for line in test.splitlines():
            lines.append(f"    {line}" if line else "")
        lines.append("")

    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    unittest.main()")
    lines.append("")
    return "\n".join(lines)


def _build_test_method(function_name, params, test_cases, returns=""):
    lines = [f"def test_{function_name}(self):"]

    if test_cases:
        for index, test_case in enumerate(test_cases, start=1):
            call_args = _format_call_args(test_case.get("args", []), test_case.get("kwargs", {}))
            expected = repr(test_case.get("expected"))
            lines.append(f"    result_{index} = {function_name}({call_args})")
            lines.append(f"    self.assertEqual(result_{index}, {expected})")
        return "\n".join(lines)

    placeholder_args = ", ".join(_placeholder_value(param) for param in params)
    lines.append(f"    result = {function_name}({placeholder_args})")

    if returns:
        lines.append("    self.assertIsNotNone(result)")
    else:
        lines.append("    self.assertTrue(True)")

    return "\n".join(lines)


def _format_call_args(args, kwargs):
    parts = [repr(item) for item in args]
    parts.extend(f"{key}={value!r}" for key, value in kwargs.items())
    return ", ".join(parts)


def _placeholder_value(param):
    name = str(param).lower()

    if "name" in name or "text" in name or "content" in name:
        return repr("test")

    if "items" in name or "list" in name:
        return repr([])

    if "data" in name or "dict" in name:
        return repr({})

    return repr(1)


def _get_params(function):
    return [arg.arg for arg in function.args.args]


def _get_return_summary(function):
    for node in ast.walk(function):
        if isinstance(node, ast.Return) and node.value is not None:
            return "value"

    return ""


def _read_text(path):
    if read_file:
        return read_file(path)

    with Path(path).open("r", encoding="utf-8") as file:
        return file.read()


def _write_text(path, content):
    if write_file:
        write_file(path, content)
        return

    with Path(path).open("w", encoding="utf-8") as file:
        file.write(content)


def _error(message):
    return {
        "success": False,
        "test_code": "",
        "file_path": "",
        "error": message,
    }
